# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 198822d803ce6cd94f86819e9929ef33af81a19d3cdec4445747f1b774dcdb4acf3c74111a7395d15004578fc6250473a71726b6b67bd83f4790db818743b474

test:
  secret_key_base: 4b3914abf18423bccd8a49dc87a1a76ab38de0323a066df1ba79b727930bb8c763ea880ca0f8521bf44f645430f2b961b9cd1aba2a0717f020fc35f34413e3f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
